# Use this in your UnturnedImages/config.yaml file
- Id: "46200-46235;46242-46319" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2972744435/items/{ItemId}.png" # The repository of the override.