# Use this in your UnturnedImages/config.yaml file
- Id: "41000-41041" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2762681465/items/{ItemId}.png" # The repository of the override.