# Use this in your UnturnedImages/config.yaml file
- Id: "14100-14106" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2959977580/items/{ItemId}.png" # The repository of the override.