# Use this in your UnturnedImages/config.yaml file
- Id: "36001-36062;36064-36282;36284-36649" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2898548949/items/{ItemId}.png" # The repository of the override.