# Use this in your UnturnedImages/config.yaml file
- Id: "26431" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2930460896/vehicles/{ItemId}.png" # The repository of the override.