# Use this in your UnturnedImages/config.yaml file
- Id: "42072" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2835565407/items/{ItemId}.png" # The repository of the override.