# Use this in your UnturnedImages/config.yaml file
- Id: "35000-35003;35005-35008" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2435496165/vehicles/{ItemId}.png" # The repository of the override.