# Use this in your UnturnedImages/config.yaml file
- Id: "34600-34602" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2938966382/items/{ItemId}.png" # The repository of the override.