# Use this in your UnturnedImages/config.yaml file
- Id: "27000-27063;27080-27099" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2955811332/vehicles/{ItemId}.png" # The repository of the override.