# Use this in your UnturnedImages/config.yaml file
- Id: "57000-57035" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2169201146/vehicles/{ItemId}.png" # The repository of the override.