# Use this in your UnturnedImages/config.yaml file
- Id: "5464" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2214081903/items/{ItemId}.png" # The repository of the override.