# Use this in your UnturnedImages/config.yaml file
- Id: "17109" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2185974859/items/{ItemId}.png" # The repository of the override.