# Use this in your UnturnedImages/config.yaml file
- Id: "786786;1800-1806;2010-2011;2013-2022;4000" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/1753131903/items/{ItemId}.png" # The repository of the override.