# Use this in your UnturnedImages/config.yaml file
- Id: "25301-25423" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/3000549606/vehicles/{ItemId}.png" # The repository of the override.