# Use this in your UnturnedImages/config.yaml file
- Id: "51255125;55900-55903" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2963851288/items/{ItemId}.png" # The repository of the override.