# Use this in your UnturnedImages/config.yaml file
- Id: "30181-30249" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2862055305/items/{ItemId}.png" # The repository of the override.