# Use this in your UnturnedImages/config.yaml file
- Id: "39000-39009;3901739017;3902539025;39033" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2907647264/items/{ItemId}.png" # The repository of the override.