# Use this in your UnturnedImages/config.yaml file
- Id: "45100-45105;45110-45127;45130-45137" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2710798455/vehicles/{ItemId}.png" # The repository of the override.