# Use this in your UnturnedImages/config.yaml file
- Id: "98009800;9805-9808" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/1762418076/items/{ItemId}.png" # The repository of the override.