# Use this in your UnturnedImages/config.yaml file
- Id: "802-849" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/1753131903/vehicles/{ItemId}.png" # The repository of the override.