# Use this in your UnturnedImages/config.yaml file
- Id: "24110" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2336509758/items/{ItemId}.png" # The repository of the override.