# Use this in your UnturnedImages/config.yaml file
- Id: "37040-37093;37170-37194" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2519307620/items/{ItemId}.png" # The repository of the override.